### PR TITLE
Prevents callTracer from crashing when tracing CeloDynamicFeeTxV2 transactions

### LINKED ISSUE #342: debug_traceBlockByNumber crash when using `withLog` setting
#### System information

```
us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth:celo-v2.0.0
```

#### Steps to reproduce the behaviour

```json
{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","id":5,"params":["0x1d9e287",{"tracer":"callTracer","timeout":"120s","tracerConfig":{"withLog":true,"onlyTopCall":false}}]}
```

#### Backtrace

````
ERROR[03-26|09:57:45.439] RPC method debug_traceBlockByNumber crashed: runtime error: index out of range [0] with length 0
goroutine 35987032 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	github.com/ethereum/go-ethereum/rpc/service.go:199 +0x85
panic({0x1af5000?, 0xc056339530?})
	runtime/panic.go:791 +0x132
github.com/ethereum/go-ethereum/eth/tracers/native.(*callTracer).OnTxEnd(0xc02ec17dc0?, 0xc0554581e8?, {0x0?, 0x0?})
	github.com/ethereum/go-ethereum/eth/tracers/native/call.go:232 +0x69
github.com/ethereum/go-ethereum/core.ApplyTransactionWithEVM.func1()
	github.com/ethereum/go-ethereum/core/state_processor.go:144 +0x2e
panic({0x1af5000?, 0xc056339518?})
	runtime/panic.go:791 +0x132
github.com/ethereum/go-ethereum/eth/tracers/native.(*callTracer).OnLog(...)
	github.com/ethereum/go-ethereum/eth/tracers/native/call.go:253
github.com/ethereum/go-ethereum/core/state.(*hookedStateDB).AddLog(0xc2e008a380, 0xc05d7d8bb0)
	github.com/ethereum/go-ethereum/core/state/statedb_hooked.go:253 +0x44
github.com/ethereum/go-ethereum/core/vm.newFrontierInstructionSet.makeLog.func54(0xc1c66c4890?, 0xc296fa2240, 0xc3f55615a8)
	github.com/ethereum/go-ethereum/core/vm/instructions.go:943 +0x31d
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc296fa2240, 0xc61797e8f0, {0xc03704e000, 0x44, 0x4000}, 0x0)
	github.com/ethereum/go-ethereum/core/vm/interpreter.go:327 +0xcbe
github.com/ethereum/go-ethereum/core/vm.(*EVM).DelegateCall(0xc0533f0900, {0x282ecc0?, 0xc61797e820?}, {0xbf, 0x83, 0xf8, 0x43, 0x6a, 0xc4, 0x6a, ...}, ...)
	github.com/ethereum/go-ethereum/core/vm/evm.go:364 +0x57c
github.com/ethereum/go-ethereum/core/vm.opDelegateCall(0xc0533f0900?, 0xc296fa2240, 0xc3f5561590)
	github.com/ethereum/go-ethereum/core/vm/instructions.go:818 +0x44b
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc296fa2240, 0xc61797e820, {0xc044b75080, 0x44, 0xf80}, 0x0)
	github.com/ethereum/go-ethereum/core/vm/interpreter.go:327 +0xcbe
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0533f0900, {0x282ecc0?, 0xc61797e750?}, {0x48, 0x6, 0x5f, 0xbb, 0xe2, 0x5f, 0x71, ...}, ...)
	github.com/ethereum/go-ethereum/core/vm/evm.go:255 +0xae5
github.com/ethereum/go-ethereum/core/vm.opCall(0xc0533f0900?, 0xc296fa2240, 0xc3f5561578)
	github.com/ethereum/go-ethereum/core/vm/instructions.go:755 +0x56d
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc296fa2240, 0xc61797e750, {0xc047685800, 0x44, 0xc00}, 0x0)
	github.com/ethereum/go-ethereum/core/vm/interpreter.go:327 +0xcbe
github.com/ethereum/go-ethereum/core/vm.(*EVM).DelegateCall(0xc0533f0900, {0x282ecc0?, 0xc61797e680?}, {0xe7, 0xaf, 0x3c, 0x1a, 0x27, 0x75, 0x5f, ...}, ...)
	github.com/ethereum/go-ethereum/core/vm/evm.go:364 +0x57c
github.com/ethereum/go-ethereum/core/vm.opDelegateCall(0xc0533f0900?, 0xc296fa2240, 0xc3f5561560)
	github.com/ethereum/go-ethereum/core/vm/instructions.go:818 +0x44b
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc296fa2240, 0xc61797e680, {0xc0533f2d20, 0x44, 0x50}, 0x0)
	github.com/ethereum/go-ethereum/core/vm/interpreter.go:327 +0xcbe
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0533f0900, {0x282d580?, 0xc0563393b0?}, {0xe, 0x2a, 0x3e, 0x5, 0xbc, 0x9a, 0x16, ...}, ...)
	github.com/ethereum/go-ethereum/core/vm/evm.go:255 +0xae5
github.com/ethereum/go-ethereum/core/vm.(*EVM).CallWithABI(0xc0533f0900, 0x0?, {0x1c092b0, 0xc}, {0xe, 0x2a, 0x3e, 0x5, 0xbc, 0x9a, ...}, ...)
	github.com/ethereum/go-ethereum/core/vm/celo_evm.go:21 +0x21d
github.com/ethereum/go-ethereum/contracts.DebitFees(0xc0533f0900, 0xc04c2d94a0, {0xb3, 0x6b, 0xe0, 0xe3, 0x3b, 0x14, 0x64, 0x11, ...}, ...)
	github.com/ethereum/go-ethereum/contracts/fee_currencies.go:64 +0x368
github.com/ethereum/go-ethereum/core.(*stateTransition).subFees(0xc05545acc0, 0xc08d919d60)
	github.com/ethereum/go-ethereum/core/celo_state_transition.go:70 +0x23d
github.com/ethereum/go-ethereum/core.(*stateTransition).buyGas(0xc05545acc0)
	github.com/ethereum/go-ethereum/core/state_transition.go:365 +0x51c
github.com/ethereum/go-ethereum/core.(*stateTransition).preCheck(0xc05545acc0)
	github.com/ethereum/go-ethereum/core/state_transition.go:493 +0x13ed
github.com/ethereum/go-ethereum/core.(*stateTransition).innerExecute(0xc05545acc0)
	github.com/ethereum/go-ethereum/core/state_transition.go:576 +0x1cf
github.com/ethereum/go-ethereum/core.(*stateTransition).execute(0xc05545acc0)
	github.com/ethereum/go-ethereum/core/state_transition.go:516 +0xf7
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc0533f0900, 0xc220249900, 0xc1c66c46b0)
	github.com/ethereum/go-ethereum/core/state_transition.go:264 +0x42f
github.com/ethereum/go-ethereum/core.ApplyTransactionWithEVM(0xc220249900, 0xc1c66c46b0, 0xc052e58300, 0xc08d9197e0, {0xf7, 0x5d, 0xfd, 0x2f, 0x7f, 0x87, ...}, ...)
	github.com/ethereum/go-ethereum/core/state_processor.go:154 +0x234
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceTx(0xc000418380, {0x283eda0, 0xc1b9f4d2c0}, 0xc152f585a0, 0xc220249900, 0xc0ef829950, {0x2624c28, 0x2624c38, 0xc5d2f14db0, 0xc08d919840, ...}, ...)
	github.com/ethereum/go-ethereum/eth/tracers/api.go:1092 +0x8fe
github.com/ethereum/go-ethereum/eth/tracers.(*API).traceBlock(0xc000418380, {0x283eda0, 0xc1b9f4d2c0}, 0xc07a12b290, 0xc3a3afb280)
	github.com/ethereum/go-ethereum/eth/tracers/api.go:668 +0xfde
github.com/ethereum/go-ethereum/eth/tracers.(*API).TraceBlockByNumber(0xc000418380, {0x283eda0, 0xc1b9f4d2c0}, 0x1d9e287, 0xc3a3afb280)
	github.com/ethereum/go-ethereum/eth/tracers/api.go:466 +0x3fc
reflect.Value.call({0xc022cc3ab0?, 0xc01dffd038?, 0xc01bc644c0?}, {0x1c00adc, 0x4}, {0xc152f584e0, 0x4, 0xc152f584e0?})
	reflect/value.go:584 +0xca6
reflect.Value.Call({0xc022cc3ab0?, 0xc01dffd038?, 0x2?}, {0xc152f584e0?, 0x16?, 0x16?})
	reflect/value.go:368 +0xb9
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc01e136000, {0x283eda0, 0xc1b9f4d2c0}, {0xc04c2d9440, 0x18}, {0xc5d2f14000, 0x2, 0x4ec8af?})
	github.com/ethereum/go-ethereum/rpc/service.go:205 +0x365
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0500d3500?, {0x283eda0?, 0xc1b9f4d2c0?}, 0xc28fcef9d0, 0x2?, {0xc5d2f14000?, 0xc0064ccd90?, 0x410690?})
	github.com/ethereum/go-ethereum/rpc/handler.go:568 +0x3c
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0cfe6c3c0, 0xc3d634dec0, 0xc28fcef9d0)
	github.com/ethereum/go-ethereum/rpc/handler.go:515 +0x235
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0cfe6c3c0, 0xc3d634dec0, 0xc28fcef9d0)
	github.com/ethereum/go-ethereum/rpc/handler.go:473 +0x22d
github.com/ethereum/go-ethereum/rpc.(*handler).handleNonBatchCall(0xc0cfe6c3c0, 0xc3d634dec0, 0xc28fcef9d0)
	github.com/ethereum/go-ethereum/rpc/handler.go:299 +0x18a
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1.1(0x283eda0?)
	github.com/ethereum/go-ethereum/rpc/handler.go:272 +0x25
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	github.com/ethereum/go-ethereum/rpc/handler.go:390 +0xbb
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc in goroutine 35546855
	github.com/ethereum/go-ethereum/rpc/handler.go:386 +0x79````

### PR DESCRIPTION
**Pull request by Kourin1996**
Fixes https://github.com/celo-org/op-geth/issues/342

This PR fixes a crash in the `callTracer` that occurs when tracing a `CeloDynamicFeeTxV2` transaction.
- Ensures that `DebitFees` and `CreditFees` do not trigger the tracer hooks binded to `HookedState`.

Relevant: https://github.com/celo-org/op-geth/pull/343

# The cause of the issue

When tracing a `CeloDynamicFeeTxV2` transaction, the functions `DebitFees` and `CreditFees` are called in addition to the standard EVM execution. These functions are supposed to be hidden from tracer like that:

```go
func DebitFees(evm *vm.EVM, feeCurrency *common.Address, address common.Address, amount *big.Int) (uint64, error) {
	// Hide this function from traces
	if evm.Config.Tracer != nil && !evm.Config.Tracer.TraceDebitCredit {
		origTracer := evm.Config.Tracer
		defer func() {
			evm.Config.Tracer = origTracer
		}()
                evm.Config.Tracer = nil
	}
```

However, `HookedState` also sets hooks of the tracer to track certain state changes:

```go
func (api *API) traceTx(ctx context.Context, tx *types.Transaction, message *core.Message, txctx *Context, vmctx vm.BlockContext, statedb *state.StateDB, config *TraceConfig) (interface{}, error) {
        ...
	tracingStateDB := state.NewHookedState(statedb, tracer.Hooks)
	evm := vm.NewEVM(vmctx, tracingStateDB, api.backend.ChainConfig(), vm.Config{Tracer: tracer.Hooks, NoBaseFee: true})
        ...
	_, err = core.ApplyTransactionWithEVM(message, new(core.GasPool).AddGas(message.GasLimit), statedb, vmctx.BlockNumber, txctx.BlockHash, tx, &usedGas, evm)
	if err != nil {
		return nil, fmt.Errorf("tracing failed: %w", err)
	}
	return tracer.GetResult()
}
```

Because of this hooking, parts of the tracer remain active. In particular, with `callTracer`, the `OnEnter` hook is never called, but `OnLog` hook is invoked. As a result, `OnLog` tries to access `callstack` that were never pushed in `OnEnter`.

```go
func (t *callTracer) OnEnter(depth int, typ byte, from common.Address, to common.Address, input []byte, gas uint64, value *big.Int) {
	t.depth = depth
	if t.config.OnlyTopCall && depth > 0 {
		return
	}
	// Skip if tracing was interrupted
	if t.interrupt.Load() {
		return
	}

	toCopy := to
	call := callFrame{
		Type:  vm.OpCode(typ),
		From:  from,
		To:    &toCopy,
		Input: common.CopyBytes(input),
		Gas:   gas,
		Value: value,
	}
	if depth == 0 {
		call.Gas = t.gasLimit
	}
	t.callstack = append(t.callstack, call)
}

func (t *callTracer) OnLog(log *types.Log) {
	// Only logs need to be captured via opcode processing
	if !t.config.WithLog {
		return
	}
	// Avoid processing nested calls when only caring about top call
	if t.config.OnlyTopCall && t.depth > 0 {
		return
	}
	// Skip if tracing was interrupted
	if t.interrupt.Load() {
		return
	}
	l := callLog{
		Address:  log.Address,
		Topics:   log.Topics,
		Data:     log.Data,
		Position: hexutil.Uint(len(t.callstack[len(t.callstack)-1].Calls)),
	}
	t.callstack[len(t.callstack)-1].Logs = append(t.callstack[len(t.callstack)-1].Logs, l)
}
```

### CODE REVIEW

**Comment by Kourin1996** [comment]
I didn't write unit tests because the mock `FeeHandler` contract never emits logs in `DebitFees`, making the issue difficult to reproduce in tests.

However, I tested a node with the changes for Alfajores and confirmed that the issue no longer occurs when tracing `CeloDynamicFeeTxV2` transactions.

File: contracts/fee_currencies.go [hunk 1]
```diff
@@ -46,10 +52,21 @@ func DebitFees(evm *vm.EVM, feeCurrency *common.Address, address common.Address,
...
+		}
+
 		defer func() {
 			evm.Config.Tracer = origTracer
+			if isHookedStateDB {
+				hookedStateDB.SetHooks(origHooks)
+			}
 		}()
-		evm.Config.Tracer = nil
 	}
```
Comment (karlb) [inline contracts/fee_currencies.go]: Since this is getting longer, would it make sense to extract it into a function?
Something like
```
reenableTracer := disableTracer(evm)
defer reenableTracer
```

File: core/state/statedb_hooked.go [hunk 2]
```diff
@@ -269,3 +269,18 @@ func (s *hookedStateDB) Finalise(deleteEmptyObjects bool) {
...
+// SetHooks provides a way to dynamically modify the Hooks,
+// since Hooks must be disabled during calls to `CreditFees` and `DebitFees`
+// Ref: contracts/fee_currencies.go
+func (s *hookedStateDB) SetHooks(hooks *tracing.Hooks) {
+	if hooks != nil {
+		s.hooks = hooks
+	} else {
+		s.hooks = new(tracing.Hooks)
+	}
+}
```
Comment (karlb) [inline core/state/statedb_hooked.go]: To avoid merge conflicts when rebasing on a more recent upstream, we often move such additions to a file with a `celo_` prefix in the same go package. In this case that would be `core/state/celo_statedb_hooked.go`. This feels a bit cluttered for such small additions, but I still consider it an overall improvement. But I might be biased since I did a lot of rebasing this year.

**Review by karlb — APPROVED** [review]
Looks good, I suggest two optional changes.

**Comment by karlb** [comment]
Regarding tests, isn't https://github.com/celo-org/op-geth/pull/343/commits/81f17e4f0d7dc8ef17bf9cf488c890ba212518f7 a valid test for this problem?

**Review by karlb — APPROVED** [review]

**Comment by pc-quiknode** [comment]
@karlb @Kourin1996 Could you make a new release for this? Thank you

**Comment by palango** [comment]
@pc-quiknode See https://github.com/celo-org/op-geth/releases/tag/celo-v2.0.4
