### PR TITLE
Fix "feeCurrency" included in non-Celo marshalled tx JSON

### LINKED ISSUE #117: Failing test: `TestSignTransaction`
After a rebase (celo5) the new test `TestSignTransaction` fails with:
```
--- FAIL: TestSignTransaction (0.00s)
   ./op-geth/internal/ethapi/api_test.go:1176: result mismatch. Have:
        {"type":"0x2","chainId":"0x1","nonce":"0x0","to":"0x703c4b2bd70c169f5717101caee543299fc946c7","gas":"0x5208","gasPrice":null,"maxPriorityFeePerGas":"0x0","maxFeePerGas":"0x684ee180","value":"0x1","input":"0x","accessList":[],"v":"0x0","r":"0x8fabeb142d585dd9247f459f7e6fe77e2520c88d50ba5d220da1533cea8b34e1","s":"0x582dd68b21aef36ba23f34e49607329c20d981d30404daf749077f5606785ce7","yParity":"0x0","hash":"0x93927839207cfbec395da84b8a2bc38b7b65d2cb2819e9fef1f091f5b1d4cc8f","feeCurrency":null}
        Want:
        {"type":"0x2","chainId":"0x1","nonce":"0x0","to":"0x703c4b2bd70c169f5717101caee543299fc946c7","gas":"0x5208","gasPrice":null,"maxPriorityFeePerGas":"0x0","maxFeePerGas":"0x684ee180","value":"0x1","input":"0x","accessList":[],"v":"0x0","r":"0x8fabeb142d585dd9247f459f7e6fe77e2520c88d50ba5d220da1533cea8b34e1","s":"0x582dd68b21aef36ba23f34e49607329c20d981d30404daf749077f5606785ce7","yParity":"0x0","hash":"0x93927839207cfbec395da84b8a2bc38b7b65d2cb2819e9fef1f091f5b1d4cc8f"}
```
        
The problem is that `"feeCurrency":null` gets added to the json-ified version of the transaction, even though it shouldn't.

See also #109

### PR DESCRIPTION
**Pull request by ezdac**
Closes #117  

Originally I thought that changing the FeeCurrency `omitempty` marshalling-behavior depending on the tx-type (Celo / non-celo txs) would be more significant code changes (see https://github.com/celo-org/op-geth/issues/117#issuecomment-2098013535). 

Thanks to struct-embedding this does not seem to be the case.

### CODE REVIEW

**Comment by ezdac** [comment]
@piersy could you give this a quick look, since you worked on #115 and there is potential overlap

File: core/types/transaction_marshalling.go [hunk 1]
```diff
@@ -150,6 +156,11 @@ func (tx *Transaction) MarshalJSON() ([]byte, error) {
 		enc.V = (*hexutil.Big)(itx.V)
 		enc.R = (*hexutil.Big)(itx.R)
 		enc.S = (*hexutil.Big)(itx.S)
+		return json.Marshal(
+			&txJSONCelo{
+				txJSON:      enc,
+				FeeCurrency: enc.FeeCurrency,
+			})
```
Comment (piersy) [inline core/types/transaction_marshalling.go]: I don't think there is any need for `txJSONCelo` you can just do the following here:
```suggestion
		enc.FeeCurrency = tx.FeeCurrency()
```

Comment (ezdac) [reply core/types/transaction_marshalling.go]: But then we would not have different behavior of marshaling the `feeCurrency` depending on which transaction type there is. We want the feeCurrency field to be excluded when we encode a non-CIP64/66 transaction and we want it to be explicitly `"feeCurrency": "null"` when a CIP64 transaction without fee-currency is encoded.
For CIP64 transactions it is possible to have a null feeCurrency, right? The [specs](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0064.md) don't say wether the field is optional or not. CIP-66 does not allow an optional feeCurrency.

We could also make it `omitempty` for all variants and never allow for encoding `"feeCurrency": "null"`

Comment (piersy) [reply core/types/transaction_marshalling.go]: Hey @ezdac, so I looked a bit deeper into this and it seems to me that the txJSON struct is just used as an intermediate decoding step that `Transaction.MarshalJSON` & `Transaction.UnmarshalJSON` rely on. So it doesn't really matter if `FeeCurrency` is marshaled as `"feeCurrency": "null"` or not at all, because in transaction marshaling/unmarshaling whether or not to include that field is determined by the transaction type that controls the internal switch statement.

So I still think just using `omitempty` should be sufficient.

Comment (ezdac) [reply core/types/transaction_marshalling.go]: Yes, for roundtrip encode - decode inside the op-geth it doesn't matter. And also nothing behaves differently for the internal Transaction type upon decoding when comparing `"feeCurrency": "null"` vs. it being left out.

We were just thinking about wether other clients interacting with the API would expect an explicit "null" for CIP64 types in terms of it being a semantic difference vs. the omission of the field. But I think this is splitting hairs and I don't see a very strong semantic reason for this, especially since CIP64 might get deprecated at some point. 

So I'll go with the simpler `omitempty` for all approach.

Comment (piersy) [reply core/types/transaction_marshalling.go]: Ahh but note the JSON encoding here is not what is provided over the RPC API.  The RPC json serialization is handled with [this](https://github.com/celo-org/op-geth/blob/celo4/internal/ethapi/api.go#L1545) struct.

Comment (ezdac) [reply core/types/transaction_marshalling.go]: Ohh okay, I should have already gotten that from your earlier comment.

Yeah makes sense - it is a little confusing that the `api_test.go` does not test the actual JSON encoding but the intermediary one. So now `omitempty` all is definitely the way to go.

Comment (piersy) [reply core/types/transaction_marshalling.go]: Yep, the encoding/decoding is highly confusing! There's also [SendTxArgs](https://github.com/celo-org/op-geth/blob/b510efe282ea4e8bfa11cfc84917644f75d0bdeb/signer/core/apitypes/types.go#L82) and [TransactionArgs](https://github.com/celo-org/op-geth/blob/b510efe282ea4e8bfa11cfc84917644f75d0bdeb/internal/ethapi/transaction_args.go#L39).

So 4 different ways and structs to JSON serialize a transaction! There could even be more, but those are the ones I'm currently aware of.

Comment (ezdac) [reply core/types/transaction_marshalling.go]: Oh, good to know, that's great - I wasn't aware of the `SendTxArgs`, but this might also be relevant for the FeeCurrency changes!
