### PR TITLE
Invalidate txs with below base-fee-floor gas-price in txpool 

### LINKED ISSUE #291: Node not rejecting txs with gas price less than 25 Gwei
### Details

* Chain: Alfajores
* Version: `us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth:celo8`
* No additional flags aside from what is documented on the docs [my config is here](https://github.com/grassrootseconomics/cel2-node/blob/master/cel2/docker-compose.yaml#L15) 

### Description

It is possible to submit type 2 transactions with a `gasFeeCap` of < 25 Gwei. This transaction will never be mined. I would expect it to be rejected at the RPC level or dropped in the tx pool. Neither of which happens. Inspecting the local txpool shows it is empty, but resubmitting the raw tx on the local or any other node results in "already known".

### Steps to reproduce

I used cast:

```bash
$ export ETH_RPC_URL=
$ cast nonce $ADDRESS
# 137
$  cast mktx --nonce 137 --gas-limit 21000 --gas-price 10gwei --priority-gas-price 10wei --private-key $PRIVATE_KEY 0x5523058cdFfe5F3c1EaDADD5015E55C6E00fb439 --value 1wei
# returns raw transaction hash
$ cast p $RAW_TRANSACTION
# Submission is successful, no error returned here, it will just wait forever forever to be mined. --async can be used to return immidiately.
$ cast decode-transactions $RAW_TRANSACTION
# Tx details
$ cast tx $TX_HASH
# Not found (never mined)
$ cast p $RAW_TX_HASH
# "already known"
```

On op-geth local node:

```bash
# Attach to IPC
> txpool.inspect
{
  pending: {},
  queued: {}
}
```

I'd expect it to show up here because of the "already known". This could be another issue.

Bumping the gasFeeCap fixes this, and resubmitting results in it being mined:

```bash
# 35 Gwei
$  cast mktx --nonce 137 --gas-limit 21000 --gas-price 35gwei --priority-gas-price 10wei --private-key $PRIVATE_KEY 0x5523058cdFfe5F3c1EaDADD5015E55C6E00fb439 --value 1wei
```

### Expected behaviour

The issue I have is that there is no way to know the status of the tx submitted with the low gas price. Ideally such a transaction is rejected immediately during submission because Celo is aware of the fee floor. On the current Celo mainnet, attempting to send a tx with a low gas price results in an immidiate error:  gasprice is less than gas price minimum floor

### PR DESCRIPTION
**Pull request by ezdac**
Fixes #291

Before, the transaction pool accepted transactions that have a gas-price below the configured base-fee-floor, which would never be executed.

Now, the transaction pool rejects those transactions immediately - giving the submitting user an immediate response and better UX.

### CODE REVIEW

File: core/txpool/celo_validation.go [hunk 1]
```diff
@@ -56,5 +61,16 @@ func CeloValidateTransaction(tx *types.Transaction, head *types.Header,
...
 
+	celoGasPrice, err := exchange.ConvertCurrencyToCelo(
+		currencyCtx.ExchangeRates,
+		tx.FeeCurrency(),
+		tx.GasFeeCap(),
+	)
+	if err != nil {
+		return err
+	}
+	if new(big.Int).SetUint64(opts.Config.Celo.EIP1559BaseFeeFloor).Cmp(celoGasPrice) == 1 {
```
Comment (palango) [inline core/txpool/celo_validation.go]: This seems to cause problems in tests, probably`Config.Celo` is `nil` in some cases.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf98521]

goroutine 5781 [running]:
github.com/ethereum/go-ethereum/core/txpool.CeloValidateTransaction(0xc001820690, 0xc0010af180?, {0x1f2b140?, 0xc000480380?}, 0xc0010af[190](https://github.com/celo-org/op-geth/actions/runs/12188965910/job/34003151772?pr=292#step:6:191), {0x0?, 0x0?})
	/runner/_work/op-geth/op-geth/core/txpool/celo_validation.go:72 +0x1a1
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).validateTxBasics(0xc0002d1800, 0xda12bf9a14d4a980?, 0x0)
	/runner/_work/op-geth/op-geth/core/txpool/legacypool/legacypool.go:667 +0x170
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).Add(0xc0002d1800, {0xc00040fc00, 0x80, 0x41e485?}, 0xa0?, 0x0)
[...]
```

**Review by palango — COMMENTED** [review]
Looks fine, but needs some additional checks to avoid test failures.

And please have a look and see if it's possible to add a test for this.

File: core/txpool/celo_validation.go (hunk 1 above)
Comment (ezdac) [reply core/txpool/celo_validation.go]: sorry, I forgot to mark the PR as draft initially

**Comment by ezdac** [comment]
@palango  After reviewing the solution again, I start to wonder:

Txpool pre-validation checks that are touched here usually try to preempt the validation that is used later during block-building, thus it is checking all conditions that **definitely** would be rejected and  hence have to be state-independent.

However in this solution, for CIP-64 transactions the check **is** state-dependent, and a transaction that is below being able to pay the base-fee-floor at the time of submission could later be executable because of a favorable fee-currency rate shift.

Do we generally want to be  strict here to favor users not having to "unstuck" a transaction from the pool,
or do we want to be over-permissive since the transaction could later on still execute once the rate changes?

Technically this is also true for the "fee-currency is allowlisted" and "currency intrinsic gas" check that is done here, but I would argue this should be assumed as "static" at this point.

Related: #304

File: core/txpool/celo_validation.go [hunk 2]
```diff
@@ -61,16 +65,34 @@ func CeloValidateTransaction(tx *types.Transaction, head *types.Header,
...
-		return err
-	}
-
 	if opts.Config.Celo != nil {
+		// Make sure that the effective gas tip at the base fee floor is at least the
+		// requested min-tip.
+		// The min-tip for local transactions is set to 0, we can skip checking here.
+		if opts.MinTip != nil && opts.MinTip.Cmp(new(big.Int)) != 0 {
+			// If not, this would never be included, so we can reject early.
+			minTip, err := exchange.ConvertCeloToCurrency(currencyCtx.ExchangeRates, tx.FeeCurrency(), opts.MinTip)
```
Comment (palango) [inline core/txpool/celo_validation.go:75]: What happens if the mintip is 1, but the exchange rate is smaller than 1? Does this get rounded to zero?

Comment (ezdac) [reply core/txpool/celo_validation.go:75]: Yes, it gets rounded to 0.
In the check, if the remaining tip after applying 25 gwei base-fee is larger or equal to the converted min-tip, 
the transaction is passed to the pool.

If the default tip is 1, but due to a higher valued fee-currency, it will be converted to 0:
This means that the transaction will not be underpriced, and thus will be forwarded to the txpool.
Within the txpool, the same conversion and check is used to filter out transactions that 
after paying for the base-fee, would undercut the required min-tip: 

https://github.com/celo-org/op-geth/blob/002a5c13ab6726ea5ce7c1f2bdc272a2b02f8514/core/txpool/legacypool/legacypool.go#L579-L582

In practice that means that if an operator does not change the default value of 1 for the min-tip,
transactions with more valuable currencies than native token would be "free" in regards to block-builder tip.

**Review by palango — APPROVED** [review]

File: core/txpool/legacypool/celo_legacypool_test.go [hunk 3]
```diff
@@ -145,3 +146,66 @@ func TestAboveBaseFeeFloorValidityCheck(t *testing.T) {
 	tx = pricedCip64Transaction(chainConfig, 2, 21000+feeCurrencyIntrinsicGas, big.NewInt(51), big.NewInt(1), &feeCurrencyTwo, key)
 	assert.NoError(t, pool.addRemote(tx))
 }
+
+func TestBelowMinTipValidityCheck(t *testing.T) {
+	t.Parallel()
+
+	baseFeeFloor := 100
+	chainConfig := celoConfig(uint64(baseFeeFloor))
```
Comment (palango) [inline core/txpool/legacypool/celo_legacypool_test.go]: Maybe worth to move those two lines into the `var` section.
