### PR TITLE
Includes baseFee in receipt of RPC response

### LINKED ISSUE #350: Recreating RLP receipts from RPC response misses baseFee
Taken from https://github.com/celo-org/celo-blockchain/discussions/2231#discussioncomment-12673169

Fee currency receipts include the base fee: https://github.com/celo-org/op-geth/blob/4fe9720b8478399f23f184904a1f3106c481af8f/core/types/celo_receipt.go#L23

But RPC responses only include the `effectiveGasPrice` derived from it. This makes it difficult to reproduce the RLP representation and its receipt hash.

Should we add the fee currency's baseFee to the RPC response?

### PR DESCRIPTION
**Pull request by Kourin1996**
Closes https://github.com/celo-org/celo-blockchain-planning/issues/956
Closes https://github.com/celo-org/op-geth/issues/350

This PR adds `baseFee` field for CeloDynamicFeeTxV2 receipt because it's necessary for calculating receipt root remotely.

## How to check

1. Run `op-geth` locally with the change of this PR

2. Switch to `alecps/receiptRootCheck` for running test code
3. Copy `core/types/receipt.go` and `core/types/gen_receipt_json.go` in this PR into the branch (This is required for mapping JSON-RPC response properly in test code)
4. Run `go run ./receipt_root_test --debug <Local RPC URL> 31123401` and make sure it passes

## How to test

I added a new script, `compat_test/hash_consistency_test.go`, which calculates BlockHash, TxHash, TxRoot, ReceiptRoot, and WithdrawalsRoot across multiple blocks starting from a specified height.

I ran a local `op-geth` node with the changes from the PR forAlfajores testnet and confirmed that the BlockHash, TxHash, TxRoot, ReceiptRoot, and WithdrawalsRoot of all L2 blocks were properly calculated based on RPC response locally

```bash
$ go test -v ./compat_test -tags compat_test -run TestHashConsistency -timeout 1h -op-geth-url ws://localhost:9994 --start-block 31056500 --block-interval 1
```

### CODE REVIEW

**Comment by palango** [comment]
@Kourin1996 This looks promising. Could you add a test case or extend an existing one (`celo_api_test.go` looks promising)

File: internal/ethapi/api.go [hunk 1]
```diff
@@ -1722,6 +1722,11 @@ func marshalReceipt(receipt *types.Receipt, blockHash common.Hash, blockNumber u
 	if receipt.ContractAddress != (common.Address{}) {
 		fields["contractAddress"] = receipt.ContractAddress
 	}
+
+	if tx.Type() == types.CeloDynamicFeeTxV2Type {
+		fields["baseFee"] = (*hexutil.Big)(receipt.BaseFee)
```
Comment (piersy) [inline internal/ethapi/api.go:1727]: CeloDyamicFeeV2Txs ocurring before the L2 start won't have the BaseFee field on the receipt, so what happens here when `receipt.BaseFee` is nil?

Comment (Kourin1996) [reply internal/ethapi/api.go:1727]: it just sets `null` to `baseFee`. But added codes to omit the field if the tx type is `CeloDynamicFeeTxV2` and the tx is for Celo1

**Comment by Kourin1996** [comment]
I tested all L2 blocks on mainnet and hashes can be calculated correctly from RPC response.

**Review by piersy — APPROVED** [review]
Looks good, thanks @Kourin1996 !

**Review by palango — APPROVED** [review]
