### PR TITLE
Get extra intrinsic gas for custom fee currency in e2e

### LINKED ISSUE #260: Update e2e tests to dynamically retreive intrinsic gas from fee currency directory
# Rationale

Currently we hardcode the value in `test_viem_tx.mjs` , but this will cause tests to fail if the value is increased in the directory.

# Implementation

We just need to call the `feeCurrencyConfig` function of the fee currency directory contract and use that value.

### PR DESCRIPTION
**Pull request by Kourin1996**
Closes https://github.com/celo-org/op-geth/issues/260

This PR adds obtaining extra IntrinsicGas cost for custom fee currency from smart contract in order to avoid failure of e2e tests due to change of its cost.

### CODE REVIEW

File: e2e_test/js-tests/test_viem_tx.mjs [hunk 1]
```diff
@@ -35,7 +35,7 @@ const testNonceBump = async (
 	const firstTxHash = await walletClient.sendTransaction({
 		to: "0x00000000000000000000000000000000DeaDBeef",
 		value: 2,
-		gas: 171000,
+		gas: await getIntrinsicGasForFeeCurrency(21000, firstCurrency),
```
Comment (ezdac) [inline e2e_test/js-tests/test_viem_tx.mjs]: nit: the value-only intrinsic gas could be defined as a test-wide constant and referenced everywhere

File: e2e_test/js-tests/test_viem_tx.mjs [hunk 2]
```diff
@@ -333,3 +332,22 @@ async function getRate(feeCurrencyAddress) {
 		toNative: (v) => (v * denominator) / numerator,
 	};
 }
+
+// getIntrinsicGasForFeeCurrency calculates intrinsic gas by adding extra intrinsic gas to the base intrinsic gas and additional cost
+async function getIntrinsicGasForFeeCurrency(baseIntrinsicGas, feeCurrency) {
+	if (!feeCurrency) return baseIntrinsicGas
```
Comment (ezdac) [inline e2e_test/js-tests/test_viem_tx.mjs]: If the other code-path always returns a BigInt, I would also cast to BigInt here.

**Review by ezdac — APPROVED** [review]
Looks good to me, apart from 2 small nit-picks.
